name: 'CI Action PHP Script'
description: ''
author: 'Shin Maung Maung'
inputs:
  user:
    description: 'GITHUB_ACTOR'
    required: true

  token:
    description: 'GITHUB_SECRET'
    required: true

  repo:
    description: 'GITHUB_REPOSITORY'
    required: true

  branch:
    description: 'GITHUB_BRANCH'
    default: 'master'

  message:
    description: 'COMMIT_MESSAGE'

  file:
    description: 'source file path in workspace [ path/to/file | path/to/file@branch ]'
  
  dest:
    description: 'default is same as `file`, destination for file output [ path/to/file | path/to/file@branch ]'

  content:
    description: 'send to input data **must not include `file`**'

runs:
   using: 'node12'
   main: 'dist/index.js'
