name: 'CI Action PHP Script'
description: ''
author: 'Shin Maung Maung'
inputs:
  user:
    description: 'github username'
    required: true
    default: ${{GITHUB_ACTOR}}

  token:
    description: 'github secret token'
    required: true

  repo:
    description: 'github repository [ ci-actions | skmetheloper/ci-actions ]'
    required: true
    default: ${{GITHUB_REPOSITORY}}

  branch:
    description: 'github branch'
    default: 'master'

  message:
    description: 'commit message'

  file:
    description: 'source file path in workspace [ path/to/file | path/to/file@branch ]'
  
  dest:
    description: 'default is same as `file`, destination for file output [ path/to/file | path/to/file@branch ]'

  content:
    description: 'send to input data **must not include `file`**'

runs:
   using: 'node12'
   main: 'index.js'
