name: CI
on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master
jobs:
  index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run-script package
    - uses: ./
      env:
        GITHUB_ACTOR: $GITHUB_ACTOR
        GITHUB_REPOSITORY: $GITHUB_REPOSITORY
      with:
        user: ${{env.GITHUB_ACTOR}}
        repo: ${{env.GITHUB_REPOSITORY}}
        token: ${{secrets.GH_SECRET}}
        message: 'built new package to `dest/index.js` file'
        file: dest/index.js
    - run: node dest/index.js

