name: CI

on:

  push:
    branches: 
    - master

  pull_request:
    branches:
    - master

jobs:

  index:
    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v2

    - uses: ./
    with:
        user: $GITHUB_USER
        token: {GITHUB_SECRET_TOKEN}
        repo: $GITHUB_WORKSPACE
        message: 'created new `package-lock.json` at `release`.'
        file: package-lock.json@master
        dest: packags-lock.json@release

    - run: npm install

    - run: npm build
